# Generated by Django 2.2.1 on 2019-05-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janusgraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshiptypemodel',
            name='name',
            field=models.CharField(choices=[('parent', 'parent'), ('child', 'child'), ('married', 'married'), ('sibling', 'sibling'), ('employer', 'employer'), ('employee', 'employee'), ('associate', 'associate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='relationshiptypemodel',
            name='reverse',
            field=models.CharField(choices=[('parent', 'parent'), ('child', 'child'), ('married', 'married'), ('sibling', 'sibling'), ('employer', 'employer'), ('employee', 'employee'), ('associate', 'associate')], max_length=50),
        ),
    ]
